
spring:
  application:
    name: sharding-jdbc
#    cloud:
#      nacos:
#        config:
#          server-addr: 127.0.0.1:8848
#        discovery:
#          server-addr: 127.0.0.1:8848

  shardingsphere:
    datasource:
      names: ds0,ds1

      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_authentication0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_authentication1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

    sharding:
      tables:
        cas_account:
          actual-data-nodes: ds${0..1}.cas_account
      default-database-strategy:
        inline:
          algorithm-expression: ds${user_no%2}
          sharding-column: user_no

#    orchestration:
#      name: orchestration-sharding-data-source
#      overwrite: false
#      registry:
#        type: zookeeper
#        serverLists: localhost:2181
#        namespace: sharding-sphere-orchestration

server:
  port: 9800
